### ISSUE TITLE
rotate_camera() got an unexpected keyword argument 'angle'

### ISSUE THREAD

**Issue by zichunxx** [elicassion/active-gym#1]
Hi! Thanks for your excellent work!

For the below code snippet, there is no keyword `angle` for the `rotate_camera` function.
https://github.com/elicassion/active-gym/blob/a05e8fd86f5f23289799fc56ff5b223486c9b797/active_gym/robosuite_env.py#L903-L905

**Comment by elicassion** [comment]
Good catch, thank you! `angle` is not used. Fixed in https://github.com/elicassion/active-gym/commit/9f98d962a6bfb8033703c7e3f766b3cea05e12a3
